@startuml
start
: user Provides getAllTheAnimalsSortedByName Method;
: System retrieves the animals;
: System sorts the animals by name ;
: return list;
end;
@enduml

@startuml
user --> AnimalShelterApp  : Sort Animals by name
AnimalShelterApp --> AnimalService : getAllTheAnimalsSortedByName()
AnimalService --> AnimalRepository : getAnimals()
AnimalService <-- AnimalRepository : List<Animal>

AnimalService --> AnimalService : sortAnimalsByName(List<Animal>)

AnimalShelterApp <-- AnimalService : return Sorted list of animals
user <-- AnimalShelterApp : get sorted list of animals



@enduml