@startuml

start

: user provides getAllAnimals method;
:print list of getAnimals;
end;
@enduml

@startuml
user--> AnimalShelterApp : input to get list of animals
AnimalShelterApp --> AnimalService : getListOfAnimals()
AnimalService --> AnimalRepository : getAnimals()
AnimalService <-- AnimalRepository : list<Animal>
AnimalShelterApp <-- AnimalService : list<Animal>
user <-- AnimalShelterApp : list<Animal>

@enduml